### ISSUE TITLE
getQuaternion() in Euler throws ERR_UNKNOWN_ORDER for Euler.ZYX

### ISSUE THREAD

**Issue by thokra1** [uber-web/math.gl#109]
There is a switch in there that evaluates the expression `this[4]` to determine the rotation order. This is incorrect and should be `this[3]` instead.

**Comment by ibgreen** [comment]
Yes that sounds like a valid bug. 

The Euler class is experimental and does not currently have good test coverage, we should try to find some time to address that.

Would you like to put up a PR? You could probably do a one-line edit it directly in the github UI... (though it would be nice with a test case that triggers the error).
