### ISSUE TITLE
Add `dist/dist.js` and `dist/dist.min.js` scripts to npm modules

### ISSUE THREAD

**Issue by ibgreen** [uber-web/math.gl#115]
- Follow other repos, like loaders.gl
- Possibly improve ocular support for building scripts

**Comment by ibgreen** [comment]
@tsherif

**Comment by luiscarbonell** [comment]
@ibgreen are you guys particular to any bundler (e.g. WebPack, Parcel, etc.)?

**Comment by ibgreen** [comment]
> @ibgreen are you guys particular to any bundler (e.g. WebPack, Parcel, etc.)?

@luiscarbonell Yes we use webpack. We also have our own helper module that packages up a bunch of JS build tools (ocular-dev-tools - it is documented [here](https://uber-web.github.io/docs/dev-tools) but admittedly we don't put nearly as much effort into those docs as we do in our user facing frameworks so they are probably both incomplete and somewhat outdated.

That said, I think the script building in loaders currently happens through: 
- https://github.com/uber-web/loaders.gl/blob/master/scripts/bundle.config.js
- https://github.com/uber-web/loaders.gl/blob/master/modules/core/package.json#L50

So it should be easy to replicate that setup by just copying that webpack file and add the build-bundle script to all the module/*/package.json files.

Are you interested in giving it a go?

**Comment by luiscarbonell** [comment]
>Are you interested in giving it a go?

I'm balancing three large-scale projects right now. But, yeah lol, I was excited to use the library in a little pet-project of mine - if I get some time this week/next I'll add it to my tickets. I like a lot of the *.gl frameworks `uber-web` has been putting out - just want to play around with them as a "guilty pleasure".

I'll shoot up a PR - if I can get around to it. :+1:

**Comment by ibgreen** [comment]
4.0 includes pre-built scripts
