### ISSUE TITLE
Broken "Get Started" docs link

### ISSUE THREAD

**Issue by kylebarron** [uber-web/math.gl#137]
The "Get Started" link on the `math.gl` homepage, points to https://math.gl/docs/developer-guide/get-started, which doesn't exist.

**Comment by ibgreen** [comment]
This was fixed on master, just redeployed the website - you may need to open dev tools and do a "hard reload" or try a different browser until the cache clears.

**Comment by kylebarron** [comment]
This is again broken for me on the published website. The current link I see is to https://math.gl/modules/core/docs/developer-guide/core-overview, which doesn't appear to exist. It seems like linking to https://math.gl/docs would be ideal.
