### ISSUE TITLE
culling: construct OBB from I3S format (quaternion)

### ISSUE THREAD

**Issue by belom88** [uber-web/math.gl#171]
It would be helpful to be able to create OrientedBoundingBox from I3S obb object which has format:
```
{
  center: [x, y, z],
  halfSize: [s1, s2, s3],
  quaternion: [x, y, z, w]
}
```
https://github.com/Esri/i3s-spec/blob/master/docs/1.7/obb.cmn.md

**Comment by ibgreen** [comment]
Closing for inactvitity.
