### ISSUE TITLE
math.gl has lookAt but not found targetTo

### ISSUE THREAD

**Issue by FreeGIS** [uber-web/math.gl#177]
in gl_matrix:
  /**
   * Generates a matrix that makes something look at something else.
   *
   * @param {mat4} out mat4 frustum matrix will be written into
   * @param {ReadonlyVec3} eye Position of the viewer
   * @param {ReadonlyVec3} center Point the viewer is looking at
   * @param {ReadonlyVec3} up vec3 pointing up
   * @returns {mat4} out
   */

  function targetTo(out, eye, target, up) 

but in math.gl only has a lookAt.I found the 'lookAt' is different from 'targetTo'

**Comment by ibgreen** [comment]
Yes, we haven't added that method.

The good news is that math.gl `Matrix4` instances are subclasses of Array so that you can use them directly with gl-matrix.

```js
import {Matrix4} from 'math.gl';
import {targetTo} from 'gl-matrix';
const matrix = new Matrix4();
targetTo(matrix, eye, target, up);
```

**Comment by ibgreen** [comment]
Close due to inactivity
