### ISSUE TITLE
I can't install this package with npm.

### ISSUE THREAD

**Issue by utb2017** [uber-web/math.gl#185]
I'm using powershell terminal. I get this error. Is there another way?

npm i @math.gl/core

At line:1 char:7
+ npm i @math.gl/core
+       ~~~~~
The splatting operator '@' cannot be used to reference variables in an expression. '@math' can be used only as an argument to a command. To reference variables in an expression use '$math'.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : SplattingNotPermitted

I got it with CMD terminal. Can close.

**Comment by saurabhcdt** [comment]
How do you solve this? I’m facing same issue.

**Comment by nemdo** [comment]
@saurabhcdt had the same problem in VSCode, but it works in the native terminal.

Just open the Command Prompt, cd to your project path and install your dependency!

**Comment by Gharla2Sami** [comment]
> @saurabhcdt had the same problem in VSCode, but it works in the native terminal.
> 
> Just open the Command Prompt, cd to your project path and install your dependency!

Thank you! This work for me

**Comment by banli17** [comment]
npm i '@math.gl/core'

**Comment by tminhbao** [comment]
> ```
> npm i '@math.gl/core'
> ```
> 
> this maybe ok

i did it, thanks
