### ISSUE TITLE
Vector3.rotateY calculates the wrong value for the x coordinate

### ISSUE THREAD

**Issue by andyblem** [uber-web/math.gl#188]
Hie. I'm not really sure if this is the right place to post my question. I'm using math.gl as my math library and I'm trying to rotate a vector to face a point/target. I have done the same calculation on paper and with the help of some online calculators and it gives me the expected result but my code doesn't.
Here's my code:
 ```
trackTarget(rotationSpeed: number, forward: Vector3, position: Vector3, target: Vector3): Vector3 {
   // calculate direction to target
    const dirToTarget = target.subtract(position);
    
    // find the axis and angle of rotation
    const dotProduct = forward.normalize().dot(dirToTarget.normalize());
    
    // calculate the angle of rotation and clamp it to max turn rate
    const unClampedAngleOfRotation: number = Math.acos(dotProduct);
    
    // rotate the forward vector now
    const rotatedForward = forward.rotateY({ radians: unClampedAngleOfRotation, origin: position });
    
    // return result
    return rotatedForward;
}
```

Here is my input:
` this.playerSteering.trackTarget(6, new Vector3(1, 0, 0), new Vector3(), new Vector3(0, 0, 1));`

Here's my expected result:
`[0,0,1]` or `[0,0,-1]`

But here is the result I get from the calculation:
`[6.123233995736766e-17, 0, -1]`

I get the correct results from every other parts of the application up until I reach the point to rotate my forward vector using the calculated angle which is in radians. Can you please help me with that.

**Comment by ibgreen** [comment]
@andyblem This seems kind of expected. Computers use finite precision floating point so there will often be small rounding errors, and 6e-17 is effectively equal to zero.

math.gl does have approximate comparison functions that accept an epsilon, if you use those `[6.123233995736766e-17, 0, -1]` and `[0,0,-1]` will compare equally.

It is possible to do rotations in a few different ways in your particular case there may be another way that preserves exact precision.

**Comment by andyblem** [comment]
I would have to simulate this and see if I get the required effect on my entity. Is there any other way you can suggest to me?

**Comment by andyblem** [comment]
You were actually correct. I couldn't get you in the first place until I read another explanation were they said the `e-17` means  `x 10 to the power -17`. That then cleared a lot of stuff for me.
