### ISSUE TITLE
Decomposing Transformations

### ISSUE THREAD

**Issue by ilan-gold** [uber-web/math.gl#195]
In the docs it is mentioned that decompositions are TBA: https://math.gl/modules/core/docs/developer-guide/transformations#decomposing-transformations

Is there a status on this?  I would be willing to make the contribution, or at least get it started, if that is something you'd be interested in.

**Comment by ibgreen** [comment]
We do have basic composition functionality now, but I can see that the docs have not kept up to date.

https://github.com/uber-web/math.gl/blob/master/modules/core/src/classes/matrix4.d.ts#L110

> I would be willing to make the contribution, ... if that is something you'd be interested in.

Yes, contributions are extremely appreciated. As you point out, it does seem like the most urgent issue is probably to do a pass on the core docs (user guide and API reference) and get them up to date, if this is something you'd consider helping with that would be great. Even a partial pass would improve things.

**Comment by ilan-gold** [comment]
Those seem to do the trick @ibgreen.  I can make a PR for this.

**Comment by ibgreen** [comment]
Doc updates published on https://math.gl website
