### ISSUE TITLE
getPolygonSignedArea could be made faster

### ISSUE THREAD

**Issue by felixpalmer** [uber-web/math.gl#212]
For context, I'm working on adding `earcut` to math.gl and it includes a method for calculating the signed area of a polygon. [Such a method](https://github.com/uber-web/math.gl/blob/cead84f7a7a7c068ad85b9cb245abe4655009e47/modules/polygon/src/polygon-utils.js#L27) is already present in the polygon modules, so it would be nice if the same code could be reused.

However, the existing method is significantly slower that the `earcut` implementation, as it involves a number of function invocations. For comparison the (slightly modified) earcut version is as follows:

```javascript
getSignedAreaOptimized() {
  const data = this.points;
  const start = 0;
  const end = this.points.length;
  const dim = this.options.size;
  let sum = 0;
  for (let i = start, j = end - dim; i < end; i += dim) {
    sum += (data[j] - data[i]) * (data[i + 1] + data[j + 1]);
    j = i;
  }
  return -sum / 2;
}
```

I've run some benchmark tests comparing the above method to the existing `Polygon.getSignedArea()` method and obtain the following:

```
┌────────────────────────────────────┬─────────┬────────────┬──────────┬──────────┐
│              (index)               │ percent │ iterations │ current  │   max    │
├────────────────────────────────────┼─────────┼────────────┼──────────┼──────────┤
│      Polygon#getSignedArea()       │   ''    │ '3.75M/s'  │ 3752127  │ 3752127  │
│  Polygon#getSignedAreaOptimized()  │   ''    │ '9.59M/s'  │ 9593674  │ 9593674  │
└────────────────────────────────────┴─────────┴────────────┴──────────┴──────────┘
```

Aside from a speed boost, the optimized version is going to put less pressure on the garbage collector.

My proposal would be to replace the the `getPolygonSignedArea` and `getPolygonSignedAreaPoints` functions with such inlined code, which would mean they could be used in the earcut implementation without a performance penalty.

**Comment by felixpalmer** [comment]
Great.

I think optimizing the nested path (`polygon.isFlatArray === false`) should be fairly straightforward, I can do that also.  

One thing that I think we can drop is the `isClosed` handling, as for the case of calculating the area it doesn't matter. If we have a duplicate point (start === end) then the `(data[j] - data[i]) * (data[i + 1] + data[j + 1])` will end up being 0 anyway. I'm just surfacing this so you don't think I've forgotten it (and to correct me in case I'm wrong!)

**Comment by ibgreen** [comment]
> I think optimizing the nested path (polygon.isFlatArray === false) should be fairly straightforward, I can do that also.

Great 

> so you don't think I've forgotten it (and to correct me in case I'm wrong!)

The best way to prove such statements without debate is to add a test case :)

**Comment by ibgreen** [comment]
@felixpalmer close?
