### ISSUE TITLE
Cannot find module "gl-matrix/vec2"

### ISSUE THREAD

**Issue by daniela-green** [uber-web/math.gl#252]
Hey, 
when installing "math.gl/web-mercator" into my project, i get several errors related to gl-matrix:
Cannot find module "gl-matrix/vec2"
Cannot find module "gl-matrix/mat4"
Steps to reproduce:

1. "@math.gl/web-mercator" version ^3.5.5
2. npm 6, node 14

Thanks,

**Comment by daniela-green** [comment]
After further debugging, i see that i do have "gl-matrix/mat4" (coming from math.gl/web-mercator),
so i dont understand how come i get this error.
Would appreciate any help with that.

![Screenshot at Oct 05 20-31-53](https://user-images.githubusercontent.com/63589197/136073643-b905424d-64b1-4f0c-b693-f8d7af2ad010.png)

**Comment by daniela-green** [comment]
Thank you @Pessimistress !!
Actually, version 3.4.1 still wasnt working for me, only resolution to 3.3.0
```
"resolutions": {
    "gl-matrix": "3.3.0"
  }
```

**Comment by kylebarron** [comment]
The related issue in gl-matrix is here: https://github.com/toji/gl-matrix/issues/439

**Comment by Pessimistress** [comment]
@kylebarron shall we just publish a new version that is pinned to 3.3.0?

**Comment by warflash** [comment]
Hey, 
when bundling my app rollup throws the same error as originally posted.
`Rollup error: Error: Cannot find module gl-matrix/vec2 `
 I'm not sure what the status of this is as the issue is still open so figured I'd ask if anyone has a working solution.
Adding 
```js
 "overrides": {
    "gl-matrix": "3.3.0"
  }
```
to my package.json as suggested does not help fix the issue unfortunately.

**Comment by ibgreen** [comment]
in 4.0 we no longer import gl-matrix, so this should be a non-issue
