### ISSUE TITLE
Is there an upgrade guide for `math.gl/web-mercator`?

### ISSUE THREAD

**Issue by Jamie5** [uber-web/math.gl#266]
We're trying to upgrade from `viewport-mercator-project` v6.2.3 to `math.gl/web-mercator` v3.5.6, and are wondering if there is a list of breaking changes and what to do about them somewhere?

e.g. currently we use things like `metersPerPixel` which no longer exists, so if a guide could e.g. point out that you can take `metersPerUnit` and do some sort of math on it to get the former `metersPerPixel` value, that would be quite helpful.

**Comment by ibgreen** [comment]
Hmm, changes like that are normally documented in https://math.gl/docs/upgrade-guide but looks like we missed this one.

The change happened here as we moved from pixel space to a more well defined world space. 

https://github.com/uber-web/math.gl/commit/098cfbfdac621dbe21afa732d96c047177d5c130#diff-fbc6c1d4c3b6db8fb54278582eb1d965ed644e97509e130346ae130da5406cb3

@Pessimistress may have some insight into how units relate to the old measure.

**Comment by ibgreen** [comment]
Close due to inactivity
