### ISSUE TITLE
Quaternion multiplyLeft/multiplyRight false type-definitions

### ISSUE THREAD

**Issue by ghost** [uber-web/math.gl#273]
The type-definitions for the Quaternion multiply functions specifies that two arguments are required.
https://github.com/uber-web/math.gl/blob/b8d331486162b37f297c4e04a6919289b75e127f/modules/core/src/classes/quaternion.d.ts#L76-L77

In the actual implementation however only one argument is allowed to be passed, leading to invalid Typescript errors.
https://github.com/uber-web/math.gl/blob/b8d331486162b37f297c4e04a6919289b75e127f/modules/core/src/classes/quaternion.js#L220-L224

**Comment by ibgreen** [comment]
This should be fixed in 4.0 as all classes are now written directly in typescript (i.e. no separate d.ts that can get out of sync)
