### ISSUE TITLE
"types" field in package.json should point to a `.d.ts` file.

### ISSUE THREAD

**Issue by latin-1** [uber-web/math.gl#282]
```diff
-  "types": "src/index.ts",
+  "types": "dist/index.d.ts",
```

`tsc` will do type-checking on that file regardless of `skipLibCheck` if that's a pure `.ts` file (not a `.d.ts` file), which may result in compile errors.

(e.g., we set `importsNotUsedAsValues` to `"error"` in our project and tsc will complain about the `.ts` files inside `node_modules/@math.gl/core`)

**Comment by Pessimistress** [comment]
Which version are you speaking of?

**Comment by latin-1** [comment]
We use v3.6.0-alpha.3 (because of inaccurate type definitions in current
stable version).

**Comment by latin-1** [comment]
@Pessimistress 
Hi, could you please release a new alpha version for this change? Thanks a lot.
