### ISSUE TITLE
Use tuple type for arrays of fixed width

### ISSUE THREAD

**Issue by Qluxzz** [uber-web/math.gl#284]
An example function: [getMapCenterByLngLatPosition](https://github.com/uber-web/math.gl/blob/f8ef4e7f2df93224fe76bc07fb6abe0921c20f4a/modules/web-mercator/src/web-mercator-viewport.ts#L353), says in the JSDoc comment that it will return an array with two elements in it `[lng,lat]`, but is typed as an array of numbers.

Typing it as `[number, number]` tuple would improve the help TypeScript can give, while also not being a breaking change(?)
https://www.typescriptlang.org/docs/handbook/2/objects.html#tuple-types

I am willing to go through and create a PR with the changes if you also feel they would improve the quality of the library.

**Comment by ibgreen** [comment]
Close due to inactivity
