### ISSUE TITLE
Missing version on yarn?

### ISSUE THREAD

**Issue by rk-yen** [uber-web/math.gl#299]
Hi,

`@math.gl/core` version 3.6.2 exists on npm registry: https://www.npmjs.com/package/@math.gl/core/v/3.6.2
But, is missing on yarn registry: https://yarnpkg.com/package/@math.gl/core
Also, on openbase: https://openbase.com/js/@math.gl/core/versions

Is this something that the team is aware of?

Thanks.

**Comment by ibgreen** [comment]
Cleaning up old issues. Seems available now.
