### ISSUE TITLE
Docs website is Not working

### ISSUE THREAD

**Issue by shaharyar-shamshi** [uber-web/math.gl#329]
Docs are hosted on the domain https://math.gl/  but it is not working

**Comment by jeffpeck10x** [comment]
still not working, 3 days later

**Comment by Pessimistress** [comment]
Website is available at https://uber-web.github.io/math.gl/. Uber owns the math.gl domain and the maintainers are trying to get in touch.

**Comment by shaharyar-shamshi** [comment]
Thank you @Pessimistress should it not be documented anywhere

**Comment by ketexon** [comment]
Could we put the working website on the main readme (at least temporarily)?
