### ISSUE TITLE
Add code coverage reporting with coveralls

### ISSUE THREAD

**Issue by tgorkin** [uber-web/math.gl#54]
We should add unit test code coverage reporting to math.gl using https://coveralls.io, similar to other vis.gl frameworks (see https://github.com/uber-web/probe.gl).

**Comment by ibgreen** [comment]
@tgorkin Add coverage to CI run https://github.com/uber-web/math.gl/blob/master/.travis.yml#L17

Do you recall what other steps to take? Enable something in coveralls? Just add a badge to README.md?

**Comment by ibgreen** [comment]
@tgorking I think we just need the badge now...
