### ISSUE TITLE
rotateAxis uses always rotateZ instead of gl-mat4/rotate.js/rotate

### ISSUE THREAD

**Issue by philogb** [uber-web/math.gl#7]
In `matrix4.js` I see:

`import mat4_rotate from 'gl-mat4/rotateZ';`

which is then used in rotateAxis. `gl-mat4/rotate/rotate` should be imported instead.

**Comment by ibgreen** [comment]
> gl-mat4/rotate/rotate should be imported instead.

@philogb Good catch. Added some test cases to help cover this case.

**Comment by philogb** [comment]
Thanks @ibgreen !
